### PR TITLE
Support multiple backends

### LINKED ISSUE #12: building with wayland support breaks x11
The ``clipcatd`` version built with build features ``all-bins``, ``x11`` and ``wayland`` returns:
```
clipcatd --no-daemon
2023-01-09T13:48:12.515061Z  INFO clipcatd is initializing, pid: 420194
2023-01-09T13:48:12.515498Z  INFO History file path: "/home/bart/.cache/clipcat/clipcatd/history.cch"
2023-01-09T13:48:12.515519Z  INFO Load history from "/home/bart/.cache/clipcat/clipcatd/history.cch"
2023-01-09T13:48:12.515696Z  INFO 79 clip(s) loaded
2023-01-09T13:48:12.515703Z  INFO Initialize ClipboardManager with capacity 500000
2023-01-09T13:48:12.515707Z  INFO Import 79 clip(s) into ClipboardManager
2023-01-09T13:48:12.515746Z  INFO Creating new wayland clipboard watcher
2023-01-09T13:48:12.515773Z  INFO Creating new wayland clipboard watcher
2023-01-09T13:48:12.515798Z ERROR Failed to load clipboard, error: Couldn't connect to the Wayland compositor. Restarting clipboard provider.
2023-01-09T13:48:12.515825Z ERROR Failed to load clipboard, error: Couldn't connect to the Wayland compositor. Restarting clipboard provider.
2023-01-09T13:48:12.515841Z  INFO gRPC service listening on 127.0.0.1:45045
2023-01-09T13:48:17.516411Z  INFO Creating new wayland clipboard watcher
2023-01-09T13:48:17.516411Z  INFO Creating new wayland clipboard watcher
2023-01-09T13:48:17.516478Z ERROR Failed to load clipboard, error: Couldn't connect to the Wayland compositor. Restarting clipboard provider.
2023-01-09T13:48:17.516478Z ERROR Failed to load clipboard, error: Couldn't connect to the Wayland compositor. Restarting clipboard provider.
2023-01-09T13:48:22.517021Z  INFO Creating new wayland clipboard watcher
2023-01-09T13:48:22.517021Z  INFO Creating new wayland clipboard watcher
2023-01-09T13:48:22.517084Z ERROR Failed to load clipboard, error: Couldn't connect to the Wayland compositor. Restarting clipboard provider.
2023-01-09T13:48:22.517084Z ERROR Failed to load clipboard, error: Couldn't connect to the Wayland compositor. Restarting clipboard provider.
2023-01-09T13:48:27.517676Z  INFO Creating new wayland clipboard watcher
2023-01-09T13:48:27.517676Z  INFO Creating new wayland clipboard watcher
2023-01-09T13:48:27.517740Z ERROR Failed to load clipboard, error: Couldn't connect to the Wayland compositor. Restarting clipboard provider.
2023-01-09T13:48:27.517741Z ERROR Failed to load clipboard, error: Couldn't connect to the Wayland compositor. Restarting clipboard provider.
2023-01-09T13:48:32.518334Z  INFO Creating new wayland clipboard watcher
2023-01-09T13:48:32.518334Z  INFO Creating new wayland clipboard watcher
2023-01-09T13:48:32.518398Z ERROR Failed to load clipboard, error: Couldn't connect to the Wayland compositor. Restarting clipboard provider.
2023-01-09T13:48:32.518398Z ERROR Failed to load clipboard, error: Couldn't connect to the Wayland compositor. Restarting clipboard provider.
^C2023-01-09T13:48:33.897762Z  INFO SIGINT received!
2023-01-09T13:48:33.897790Z  INFO Shutting down cleanly. Interrupt again to shut down immediately.
2023-01-09T13:48:33.897826Z  INFO ClipboardWorker is shutting down gracefully
2023-01-09T13:48:33.897858Z  INFO Save history and shrink to capacity 500000
2023-01-09T13:48:33.897871Z  INFO gRPC service is shutting down gracefully
2023-01-09T13:48:33.897952Z  INFO gRPC service is down
2023-01-09T13:48:33.913525Z  INFO ClipboardWorker is down
2023-01-09T13:48:33.913610Z  INFO clipcatd is shutdown
```
It does not work.

The one without ``wayland`` works, but oddly enough also mentions wayland, though only once:
```
clipcatd --no-daemon
2023-01-09T14:08:27.663635Z  INFO clipcatd is initializing, pid: 438303
2023-01-09T14:08:27.664095Z  INFO History file path: "/home/bart/.cache/clipcat/clipcatd/history.cch"
2023-01-09T14:08:27.664128Z  INFO Load history from "/home/bart/.cache/clipcat/clipcatd/history.cch"
2023-01-09T14:08:27.664297Z  INFO 80 clip(s) loaded
2023-01-09T14:08:27.664305Z  INFO Initialize ClipboardManager with capacity 500000
2023-01-09T14:08:27.664312Z  INFO Import 80 clip(s) into ClipboardManager
2023-01-09T14:08:27.665113Z  INFO gRPC service listening on 127.0.0.1:45045
2023-01-09T14:08:27.715552Z  INFO Clipboard ["Failed to load clipboard, error: Couldn't connect to the Wayland compositor. Restarting clipboard provider."]
2023-01-09T14:08:27.716294Z  INFO Primary ["Failed to load clipboard, error: Couldn't connect to the Wayland compositor. Restarting clipboard provider."]
2023-01-09T14:08:47.146872Z  INFO Primary ["Nothing"]
2023-01-09T14:08:47.312524Z  INFO Primary ["2023-01-09T14:08:43.814408Z  INFO Nothing is selected\n"]
```

In all cases, I'm running ``0.6.0`` on X11.

### PR DESCRIPTION
**Pull request by Icelk**
Fixes #12

### CODE REVIEW

**Comment by wrvsrx** [comment]
Current implementation has a bug. You might think that https://github.com/Icelk/clipcat/blob/ca48a5da00bb00d93641ff5401cef656a18fe190/src/monitor.rs#L242 can catch error when there is no wayland compositer. However, it's not. Error won't be thrown until `load_wait()` is called. I think which compositer is running (wayland or X11) should be tested in a better way here.

**Comment by Icelk** [comment]
Good eye! It's a bit problematic that I now only use Wayland. I don't catch the X11 bugs...
I just pushed 19d9708. Does that address the regression for you?

**Comment by wrvsrx** [comment]
Thank you! It fixed my problem. Would you consider use method in https://github.com/1Password/arboard/blob/e1f521f47d60b4cd0f440870608cf24d2db8acb0/src/platform/linux/mod.rs#L77-L97to detect compositor?

**Comment by Icelk** [comment]
I initially feel like the method we use now is more abstract, which is a good thing. wl_clipboard naturally does this - so we don't have to. One can also pass a custom compositor path to wl_clipboard, in which case the env variable isn't needed. What advantages do you see in checking the env variable?

**Comment by wrvsrx** [comment]
1. There are many reasons can make `load`
 
 https://github.com/Icelk/clipcat/blob/19d9708cdcfcb69d4a01e0576c554e9e1a73f9b9/src/monitor.rs#L244

fail. Its failure doesn't mean there isn't wayland compositor running.

2. `WAYLAND_DISPLAY` is the documented way to determine if wayland is runnning. (https://docs.fedoraproject.org/en-US/fedora/latest/system-administrators-guide/Wayland/)

**Comment by Icelk** [comment]
Great point!

**Comment by Icelk** [comment]
This is now implemented.

**Pull request merged**
